services:
  usuarios-mysql:
    image: mysql:latest
    container_name: user-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
    ports:
      - 3306:3306

  user-API:
    image: api-user-image
    container_name: api-user-container
    ports:
      - 8080:8080
    depends_on:
      - user-mysql

  mongo-products:
    image: mongo:latest
    container_name: mongo-products

  product-API:
    image: api-products-image
    container_name: api-products-container
    ports:
      - 8081:8081
    depends_on:
      - mongo-products

  mongo-carts:
    image: mongo:latest
    container_name: mongo-carts
    command: mongod -port 27018
    ports:
      - 27018:27018

  cart-API:
    image: api-cart-image
    container_name: api-cart-container
    ports:
      - 8082:8082
    depends_on:
      - mongo-carts

mongo-sales:
  image: mongo:latest
  container_name: mongo-sales
  hostname: mongo-sales
  ports:
    - 27019:27019


  salesAPI:
    image: api-sales-image
    container_name: api-sales-container
    ports:
      - 80:80
    depends_on:
      - user-API
      - product-API
      - cart-API
      - mongo-sales








